name: codespell
on:
  push:
    branches: [main]
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
