name: vale
on:
  push:
    branches: [main]
  pull_request:

jobs:
  vale:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
